server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:book-service
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
    schema: schema.sql
    data: data.sql
  h2:
    console:
      enabled: true
