server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:book-service
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: schema.sql
      data-locations: data.sql
  h2:
    console:
      enabled: true
  liquibase:
    change-log: db/changelog/changelog-liquibase.xml
