DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS author;
DROP TABLE IF EXISTS genre;

CREATE TABLE book (
    id LONG AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    author_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL
);

CREATE TABLE author (
  id LONG AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

CREATE TABLE genre (
  id LONG AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);